/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

/**
 *
 * @author strawtech
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSueldo = new javax.swing.JLabel();
        CajaSueldo = new javax.swing.JTextField();
        txtAux = new javax.swing.JLabel();
        CajaAux = new javax.swing.JTextField();
        txtSuma = new javax.swing.JLabel();
        CajaSuma = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        CajaSueldoAnual = new javax.swing.JTextField();
        CajaAuxAnual = new javax.swing.JTextField();
        txtCesantias = new javax.swing.JLabel();
        CajaCesantias = new javax.swing.JTextField();
        CajaCesantiasAnual = new javax.swing.JTextField();
        txtDiasLab = new javax.swing.JLabel();
        jcbDias = new javax.swing.JComboBox<>();
        txtInteresCesantias = new javax.swing.JLabel();
        CajaInteres = new javax.swing.JTextField();
        CajaInteresAnual = new javax.swing.JTextField();
        txtPrimaLegal = new javax.swing.JLabel();
        CajaPrima = new javax.swing.JTextField();
        CajaPrimaAnual = new javax.swing.JTextField();
        txtVacaciones = new javax.swing.JLabel();
        CajaVacaciones = new javax.swing.JTextField();
        CajaVacacionesAnual = new javax.swing.JTextField();
        txtSalud = new javax.swing.JLabel();
        CajaSalud = new javax.swing.JTextField();
        CajaSaludAnual = new javax.swing.JTextField();
        txtPension = new javax.swing.JLabel();
        CajaPension = new javax.swing.JTextField();
        CajaPensionAnual = new javax.swing.JTextField();
        txtParafiscales = new javax.swing.JLabel();
        txtSena = new javax.swing.JLabel();
        CajaSena = new javax.swing.JTextField();
        CajaSenaAnual = new javax.swing.JTextField();
        txticbf = new javax.swing.JLabel();
        CajaICBF = new javax.swing.JTextField();
        CajaICBFAnual = new javax.swing.JTextField();
        txtCajaCompensacion = new javax.swing.JLabel();
        CajaCompensacion = new javax.swing.JTextField();
        CajaCompensacionAnual = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();
        CajaTotal = new javax.swing.JTextField();
        CajaTotalAnual = new javax.swing.JTextField();
        PanelPorcentaje = new javax.swing.JPanel();
        txtSaludPorcentaje = new javax.swing.JLabel();
        CajaSaludPorcentaje = new javax.swing.JTextField();
        txtPensionPorcentaje = new javax.swing.JLabel();
        CajaPensionPorcentaje = new javax.swing.JTextField();
        txtSenaPorcentaje = new javax.swing.JLabel();
        CajaSenaPorcentaje = new javax.swing.JTextField();
        txtICBFPorcentaje = new javax.swing.JLabel();
        CajaICBFPension = new javax.swing.JTextField();
        txtCompensacionPorcentaje = new javax.swing.JLabel();
        CajaCompensacionPorcentaje = new javax.swing.JTextField();
        txtMensual = new javax.swing.JLabel();
        txtAnual = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSueldo.setText("Sueldo");

        txtAux.setText("Aux Transporte");

        txtSuma.setText("Aux T+Sueldo");

        CajaSuma.setEditable(false);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        CajaSueldoAnual.setEditable(false);

        CajaAuxAnual.setEditable(false);

        txtCesantias.setText("Cesantias");

        CajaCesantias.setEditable(false);

        CajaCesantiasAnual.setEditable(false);

        txtDiasLab.setText("Dias Laborados");

        jcbDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "35", "60", "120", "240", "360" }));

        txtInteresCesantias.setText("Interes cesantias");

        CajaInteres.setEditable(false);

        CajaInteresAnual.setEditable(false);

        txtPrimaLegal.setText("Prima legal");

        CajaPrima.setEditable(false);

        CajaPrimaAnual.setEditable(false);

        txtVacaciones.setText("Vacaciones");

        CajaVacaciones.setEditable(false);

        CajaVacacionesAnual.setEditable(false);

        txtSalud.setText("Salud");

        CajaSalud.setEditable(false);

        CajaSaludAnual.setEditable(false);

        txtPension.setText("Pension");

        CajaPension.setEditable(false);

        CajaPensionAnual.setEditable(false);

        txtParafiscales.setText("Parafisiscales");
        txtParafiscales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtSena.setText("Sena");

        CajaSena.setEditable(false);

        CajaSenaAnual.setEditable(false);

        txticbf.setText("ICBF");

        CajaICBF.setEditable(false);

        CajaICBFAnual.setEditable(false);

        txtCajaCompensacion.setText("Caja Compensacion");

        CajaCompensacion.setEditable(false);

        CajaCompensacionAnual.setEditable(false);

        txtTotal.setText("Total");

        CajaTotal.setEditable(false);

        CajaTotalAnual.setEditable(false);
        CajaTotalAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaTotalAnualActionPerformed(evt);
            }
        });

        txtSaludPorcentaje.setText("Salud");

        CajaSaludPorcentaje.setEditable(false);
        CajaSaludPorcentaje.setText("4%");

        txtPensionPorcentaje.setText("Pension");

        CajaPensionPorcentaje.setEditable(false);
        CajaPensionPorcentaje.setText("4%");

        txtSenaPorcentaje.setText("Sena");

        CajaSenaPorcentaje.setEditable(false);
        CajaSenaPorcentaje.setText("2%");

        txtICBFPorcentaje.setText("ICBF");

        CajaICBFPension.setEditable(false);
        CajaICBFPension.setText("3%");

        txtCompensacionPorcentaje.setText("Caja Compensacion");

        CajaCompensacionPorcentaje.setEditable(false);
        CajaCompensacionPorcentaje.setText("4%");

        javax.swing.GroupLayout PanelPorcentajeLayout = new javax.swing.GroupLayout(PanelPorcentaje);
        PanelPorcentaje.setLayout(PanelPorcentajeLayout);
        PanelPorcentajeLayout.setHorizontalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                        .addComponent(txtSaludPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(CajaSaludPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                        .addComponent(txtPensionPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(CajaPensionPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                        .addComponent(txtSenaPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(CajaSenaPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                        .addComponent(txtICBFPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(CajaICBFPension, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                        .addComponent(txtCompensacionPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(CajaCompensacionPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        PanelPorcentajeLayout.setVerticalGroup(
            PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorcentajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaludPorcentaje)
                    .addComponent(CajaSaludPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPensionPorcentaje)
                    .addComponent(CajaPensionPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenaPorcentaje)
                    .addComponent(CajaSenaPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtICBFPorcentaje)
                    .addComponent(CajaICBFPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompensacionPorcentaje)
                    .addComponent(CajaCompensacionPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtMensual.setText("Mensual");

        txtAnual.setText("Anual");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(txtTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CajaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CajaTotalAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(txtSueldo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CajaSueldoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtCajaCompensacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CajaCompensacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CajaCompensacionAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtCesantias)
                                                    .addGap(51, 51, 51)
                                                    .addComponent(CajaCesantias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(CajaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtAux)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CajaAux, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CajaAuxAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaCesantiasAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtPension)
                                                    .addGap(65, 65, 65)
                                                    .addComponent(CajaPension, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtSalud)
                                                    .addGap(81, 81, 81)
                                                    .addComponent(CajaSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtVacaciones)
                                                    .addGap(43, 43, 43)
                                                    .addComponent(CajaVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtPrimaLegal)
                                                    .addGap(42, 42, 42)
                                                    .addComponent(CajaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtInteresCesantias)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CajaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CajaInteresAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaPrimaAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaVacacionesAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaSaludAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaPensionAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtParafiscales, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 12, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txticbf)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CajaICBF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtSena)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CajaSena, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(31, 31, 31)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CajaSenaAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CajaICBFAnual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(txtMensual)
                                .addGap(68, 68, 68)
                                .addComponent(txtAnual)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSuma)
                                .addGap(18, 18, 18)
                                .addComponent(CajaSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDiasLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbDias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSuma)
                            .addComponent(CajaSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMensual, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAnual, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSueldo)
                            .addComponent(CajaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaSueldoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAux)
                            .addComponent(CajaAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaAuxAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiasLab)
                            .addComponent(jcbDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CajaCesantias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CajaCesantiasAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCesantias))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInteresCesantias)
                            .addComponent(CajaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaInteresAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrimaLegal)
                            .addComponent(CajaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaPrimaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVacaciones)
                            .addComponent(CajaVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaVacacionesAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalud)
                            .addComponent(CajaSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaSaludAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPension)
                            .addComponent(CajaPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaPensionAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtParafiscales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaSenaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSena)
                                .addComponent(CajaSena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txticbf)
                            .addComponent(CajaICBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaICBFAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCajaCompensacion)
                            .addComponent(CajaCompensacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaCompensacionAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal)
                            .addComponent(CajaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaTotalAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(PanelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcular)
                            .addComponent(btnLimpiar)
                            .addComponent(btnSalir))
                        .addGap(138, 138, 138))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        //variables
        int sueldo,aux_t,totalsumas,anio1,aux_anio,dias,interesdos,vacaciones,vacaciones_anual,salud,saluddos,pension,pensiondos,sena,senados,icbf,icbfdos,compensacion,compensaciondos,totalmensual,totalanual;
        float interes,cesantias,aniodos;
    
        //String a numerico
        sueldo=Integer.parseInt(CajaSueldo.getText()); //sueldo mensual
        aux_t=Integer.parseInt(CajaAux.getText()); //sueldo anual
        dias=Integer.parseInt((String) jcbDias.getSelectedItem());
        
        
        //operaciones
        //int sueldo_dos = Math.round(sueldo);
        totalsumas = sueldo+aux_t;
        anio1 = (sueldo*12);
        aux_anio = (aux_t*12);
        cesantias = (sueldo*dias)/360;
        int cesantiasuno = Math.round(cesantias);
        aniodos = (cesantias*12);
        int cesantias_anul = Math.round(aniodos);
        //interes = (cesantias*0.12f*interes)/360; //interes=(valorcesantias*12%*diastrabajados)/360
        interes = (cesantias*0.12f*dias)/360;
        int interesuno = Math.round(interes);
        interesdos = (interesuno*12);
        vacaciones = (566700*360)/720;
        vacaciones_anual = (vacaciones*12);
        salud = (sueldo*4)/100;
        //int saluduno = Math.round(salud);
        saluddos = (salud*12);
        pension = (sueldo*4)/100;
        //int pensiouno = Math.round(pension);
        pensiondos = (pension*12);
        sena = (sueldo*2)/100;
        //int senauno = Math.round(sena);
        senados = (sena*12);
        icbf = (sueldo*3)/100;
        //int icbfuno = Math.round(icbf);
        icbfdos = (icbf*12);
        compensacion = (sueldo*4)/100;
        //int compensacion_uno = Math.round(compensacion);
        compensaciondos = (compensacion*12);
        totalmensual = (sueldo+aux_t+cesantiasuno+interesuno+cesantiasuno+vacaciones+salud+pension+sena+icbf+compensacion);
        totalanual = (anio1+aux_anio+cesantias_anul+interesdos+cesantias_anul+vacaciones_anual+pensiondos+senados+icbfdos+compensaciondos);
        
        
        //Mostrar resultado
        CajaSuma.setText(String.valueOf(totalsumas)); //Aux T+Sueldo
        CajaSueldoAnual.setText(String.valueOf(anio1)); //sueldo anual
        CajaAuxAnual.setText(String.valueOf(aux_anio)); //aux anual
        CajaCesantias.setText(String.valueOf(cesantiasuno)); //cesantias mensual
        CajaCesantiasAnual.setText(String.valueOf(cesantias_anul)); //cesantias anual
        CajaInteres.setText(String.valueOf(interesuno)); //interes cesantias mensual
        CajaInteresAnual.setText(String.valueOf(interesdos)); //interes anual
        CajaPrima.setText(String.valueOf(cesantiasuno)); //prima mensual
        CajaPrimaAnual.setText(String.valueOf(cesantias_anul)); //prima anual
        CajaVacaciones.setText(String.valueOf(vacaciones)); //vacaciones mensual
        CajaVacacionesAnual.setText(String.valueOf(vacaciones_anual)); //vacaciones anual
        CajaSalud.setText(String.valueOf(salud)); // salud mensaul
        CajaSaludAnual.setText(String.valueOf(saluddos)); //salud anual
        CajaPension.setText(String.valueOf(pension)); //pension mensual
        CajaPensionAnual.setText(String.valueOf(pensiondos)); //pension anual
        CajaSena.setText(String.valueOf(sena)); //sena mensual
        CajaSenaAnual.setText(String.valueOf(senados)); //sena anual
        CajaICBF.setText(String.valueOf(icbf)); //icbf mensual
        CajaICBFAnual.setText(String.valueOf(icbfdos)); //icbf anual
        CajaCompensacion.setText(String.valueOf(compensacion)); //compensacion mensual
        CajaCompensacionAnual.setText(String.valueOf(compensaciondos)); //compensacion anual
        CajaTotal.setText(String.valueOf(totalmensual)); //total mensual
        CajaTotalAnual.setText(String.valueOf(totalanual)); //total anual
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void CajaTotalAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaTotalAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaTotalAnualActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
    //limpiar todos los datos    
    CajaSueldo.setText("");
    CajaSueldoAnual.setText("");
    CajaAux.setText("");
    CajaAuxAnual.setText("");
    CajaCesantias.setText("");
    CajaCesantiasAnual.setText("");
    CajaInteres.setText("");
    CajaInteresAnual.setText("");
    CajaPrima.setText("");
    CajaPrimaAnual.setText("");
    CajaVacaciones.setText("");
    CajaVacacionesAnual.setText("");
    CajaSalud.setText("");
    CajaSaludAnual.setText("");
    CajaPension.setText("");
    CajaPensionAnual.setText("");
    CajaSena.setText("");
    CajaSenaAnual.setText("");
    CajaICBF.setText("");
    CajaICBFAnual.setText("");
    CajaCompensacion.setText("");
    CajaCompensacionAnual.setText("");
    CajaTotal.setText("");
    CajaTotalAnual.setText("");
    CajaSuma.setText("");
    jcbDias.removeAllItems();
    
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       
        //salir del programa
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaAux;
    private javax.swing.JTextField CajaAuxAnual;
    private javax.swing.JTextField CajaCesantias;
    private javax.swing.JTextField CajaCesantiasAnual;
    private javax.swing.JTextField CajaCompensacion;
    private javax.swing.JTextField CajaCompensacionAnual;
    private javax.swing.JTextField CajaCompensacionPorcentaje;
    private javax.swing.JTextField CajaICBF;
    private javax.swing.JTextField CajaICBFAnual;
    private javax.swing.JTextField CajaICBFPension;
    private javax.swing.JTextField CajaInteres;
    private javax.swing.JTextField CajaInteresAnual;
    private javax.swing.JTextField CajaPension;
    private javax.swing.JTextField CajaPensionAnual;
    private javax.swing.JTextField CajaPensionPorcentaje;
    private javax.swing.JTextField CajaPrima;
    private javax.swing.JTextField CajaPrimaAnual;
    private javax.swing.JTextField CajaSalud;
    private javax.swing.JTextField CajaSaludAnual;
    private javax.swing.JTextField CajaSaludPorcentaje;
    private javax.swing.JTextField CajaSena;
    private javax.swing.JTextField CajaSenaAnual;
    private javax.swing.JTextField CajaSenaPorcentaje;
    private javax.swing.JTextField CajaSueldo;
    private javax.swing.JTextField CajaSueldoAnual;
    private javax.swing.JTextField CajaSuma;
    private javax.swing.JTextField CajaTotal;
    private javax.swing.JTextField CajaTotalAnual;
    private javax.swing.JTextField CajaVacaciones;
    private javax.swing.JTextField CajaVacacionesAnual;
    private javax.swing.JPanel PanelPorcentaje;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbDias;
    private javax.swing.JLabel txtAnual;
    private javax.swing.JLabel txtAux;
    private javax.swing.JLabel txtCajaCompensacion;
    private javax.swing.JLabel txtCesantias;
    private javax.swing.JLabel txtCompensacionPorcentaje;
    private javax.swing.JLabel txtDiasLab;
    private javax.swing.JLabel txtICBFPorcentaje;
    private javax.swing.JLabel txtInteresCesantias;
    private javax.swing.JLabel txtMensual;
    private javax.swing.JLabel txtParafiscales;
    private javax.swing.JLabel txtPension;
    private javax.swing.JLabel txtPensionPorcentaje;
    private javax.swing.JLabel txtPrimaLegal;
    private javax.swing.JLabel txtSalud;
    private javax.swing.JLabel txtSaludPorcentaje;
    private javax.swing.JLabel txtSena;
    private javax.swing.JLabel txtSenaPorcentaje;
    private javax.swing.JLabel txtSueldo;
    private javax.swing.JLabel txtSuma;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtVacaciones;
    private javax.swing.JLabel txticbf;
    // End of variables declaration//GEN-END:variables
}
